/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2014 StuxCrystal
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package net.stuxcrystal.jass;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Returns the section for the info.
 */
public class AssInfoSection extends AssSection<AssInfoEntry> {

    @Override
    public String getSectionTitle() {
        return "Script Info";
    }

    @Override
    public List<AssInfoEntry> parse(List<String> lines) {
        List<AssInfoEntry> result = new ArrayList<>();

        for (String line : lines) {

            // Ignore comments.
            if (line.startsWith(";"))
                continue;

            if (!line.contains(":"))
                continue;

            String[] data = line.split(":[ ]*", 2);
            result.add(new AssInfoEntry(data[0], data[1]));
        }

        return result;
    }

    @Override
    public List<String> dump(List<AssInfoEntry> rawEntries) {
        // Enfore
        List<String> result = new ArrayList<>(Arrays.asList("; Generated by jAss " + AssLibraryData.VERSION));
        List<AssInfoEntry> entries = new ArrayList<>(rawEntries);

        // Find the header entry.
        AssInfoEntry header = null;
        for (AssInfoEntry entry : entries) {
            if (entry.getKey().equalsIgnoreCase("Header")) {
                header = entry;
                break;
            }
        }

        // Remove the entry if there is one and print the header.
        if (header!=null) {
            entries.remove(header);
            for (String line : header.getValue().split("\n")) {
                result.add("; " + line);
            }
        }

        // Prints all entries.
        for (AssInfoEntry entry : entries) {
            result.add(entry.getKey() + ": " + entry.getValue());
        }

        return result;
    }
}
